version: '3'
services:
    nginx:
        image: nginx:1.17-alpine
        container_name: "laravel_tutorial_blog_nginx"
        ports:
            - ${IP}:80:80
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
    php-fpm:
        build: ./docker/php
        image: "php-fpm:latest"
        container_name: "laravel_tutorial_blog_php-fpm"
        volumes:
            - ./src:/var/www
        links:
            - db
        depends_on:
            - db
    db:
        image: mysql:8.0.18
        container_name: "laravel_tutorial_blog_db"
        volumes:
            - ./docker/mysql/conf.d:/etc/mysql/conf.d
            - ./docker/mysql/data:/var/lib/mysql
        ports:
            - ${IP}:3306:3306
        environment:
            MYSQL_DATABASE: laravel-tutorial-blog
            MYSQL_USER: sample
            MYSQL_PASSWORD: sample
            MYSQL_ROOT_PASSWORD: root
            TZ: "Asia/Tokyo"
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci